
  create table "public"."deal_products" (
    "id" bigint generated by default as identity not null,
    "deal_id" bigint not null,
    "product_id" bigint not null,
    "quantity" integer not null default 1,
    "unit_price" numeric not null default 0
      );


alter table "public"."deal_products" enable row level security;


  create table "public"."deal_services" (
    "id" bigint generated by default as identity not null,
    "deal_id" bigint not null,
    "service_id" bigint not null,
    "quantity" integer not null default 1,
    "unit_price" numeric not null default 0
      );


alter table "public"."deal_services" enable row level security;


  create table "public"."maintenance_contracts" (
    "id" bigint generated by default as identity not null,
    "company_id" bigint not null,
    "service_id" bigint not null,
    "deal_id" bigint,
    "start_date" date not null,
    "end_date" date not null,
    "status" text not null default 'active'::text,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."maintenance_contracts" enable row level security;


  create table "public"."products" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text,
    "price" numeric not null default 0,
    "active" boolean not null default true,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."products" enable row level security;


  create table "public"."services" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "type" text,
    "periodicity_months" integer not null default 12,
    "price" numeric not null default 0,
    "description" text,
    "active" boolean not null default true,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."services" enable row level security;

CREATE INDEX deal_products_deal_id_idx ON public.deal_products USING btree (deal_id);

CREATE UNIQUE INDEX deal_products_pkey ON public.deal_products USING btree (id);

CREATE INDEX deal_services_deal_id_idx ON public.deal_services USING btree (deal_id);

CREATE UNIQUE INDEX deal_services_pkey ON public.deal_services USING btree (id);

CREATE INDEX maintenance_contracts_company_id_idx ON public.maintenance_contracts USING btree (company_id);

CREATE INDEX maintenance_contracts_end_date_idx ON public.maintenance_contracts USING btree (end_date);

CREATE UNIQUE INDEX maintenance_contracts_pkey ON public.maintenance_contracts USING btree (id);

CREATE UNIQUE INDEX products_pkey ON public.products USING btree (id);

CREATE UNIQUE INDEX services_pkey ON public.services USING btree (id);

alter table "public"."deal_products" add constraint "deal_products_pkey" PRIMARY KEY using index "deal_products_pkey";

alter table "public"."deal_services" add constraint "deal_services_pkey" PRIMARY KEY using index "deal_services_pkey";

alter table "public"."maintenance_contracts" add constraint "maintenance_contracts_pkey" PRIMARY KEY using index "maintenance_contracts_pkey";

alter table "public"."products" add constraint "products_pkey" PRIMARY KEY using index "products_pkey";

alter table "public"."services" add constraint "services_pkey" PRIMARY KEY using index "services_pkey";

alter table "public"."deal_products" add constraint "deal_products_deal_id_fkey" FOREIGN KEY (deal_id) REFERENCES public.deals(id) ON DELETE CASCADE not valid;

alter table "public"."deal_products" validate constraint "deal_products_deal_id_fkey";

alter table "public"."deal_products" add constraint "deal_products_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) not valid;

alter table "public"."deal_products" validate constraint "deal_products_product_id_fkey";

alter table "public"."deal_services" add constraint "deal_services_deal_id_fkey" FOREIGN KEY (deal_id) REFERENCES public.deals(id) ON DELETE CASCADE not valid;

alter table "public"."deal_services" validate constraint "deal_services_deal_id_fkey";

alter table "public"."deal_services" add constraint "deal_services_service_id_fkey" FOREIGN KEY (service_id) REFERENCES public.services(id) not valid;

alter table "public"."deal_services" validate constraint "deal_services_service_id_fkey";

alter table "public"."maintenance_contracts" add constraint "maintenance_contracts_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE not valid;

alter table "public"."maintenance_contracts" validate constraint "maintenance_contracts_company_id_fkey";

alter table "public"."maintenance_contracts" add constraint "maintenance_contracts_deal_id_fkey" FOREIGN KEY (deal_id) REFERENCES public.deals(id) not valid;

alter table "public"."maintenance_contracts" validate constraint "maintenance_contracts_deal_id_fkey";

alter table "public"."maintenance_contracts" add constraint "maintenance_contracts_service_id_fkey" FOREIGN KEY (service_id) REFERENCES public.services(id) not valid;

alter table "public"."maintenance_contracts" validate constraint "maintenance_contracts_service_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.create_maintenance_contracts_on_win()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
    -- Only trigger when stage changes to 'won'
    if (old.stage is distinct from new.stage and new.stage = 'won') then
        insert into public.maintenance_contracts (company_id, service_id, deal_id, start_date, end_date)
        select
            new.company_id,
            ds.service_id,
            new.id,
            current_date,
            current_date + (s.periodicity_months || ' months')::interval
        from public.deal_services ds
        join public.services s on s.id = ds.service_id
        where ds.deal_id = new.id;
    end if;
    return new;
end;
$function$
;

create or replace view "public"."companies_summary" as  SELECT c.id,
    c.created_at,
    c.name,
    c.sector,
    c.size,
    c.linkedin_url,
    c.website,
    c.phone_number,
    c.address,
    c.zipcode,
    c.city,
    c.state_abbr,
    c.sales_id,
    c.context_links,
    c.country,
    c.description,
    c.revenue,
    c.tax_identifier,
    c.logo,
    count(DISTINCT d.id) AS nb_deals,
    count(DISTINCT co.id) AS nb_contacts,
    (EXISTS ( SELECT 1
           FROM (public.deal_products dp
             JOIN public.deals d2 ON ((d2.id = dp.deal_id)))
          WHERE (d2.company_id = c.id))) AS has_equipment,
    (EXISTS ( SELECT 1
           FROM public.maintenance_contracts mc
          WHERE ((mc.company_id = c.id) AND (mc.end_date > now())))) AS has_maintenance
   FROM ((public.companies c
     LEFT JOIN public.deals d ON ((c.id = d.company_id)))
     LEFT JOIN public.contacts co ON ((c.id = co.company_id)))
  GROUP BY c.id;


grant delete on table "public"."deal_products" to "anon";

grant insert on table "public"."deal_products" to "anon";

grant references on table "public"."deal_products" to "anon";

grant select on table "public"."deal_products" to "anon";

grant trigger on table "public"."deal_products" to "anon";

grant truncate on table "public"."deal_products" to "anon";

grant update on table "public"."deal_products" to "anon";

grant delete on table "public"."deal_products" to "authenticated";

grant insert on table "public"."deal_products" to "authenticated";

grant references on table "public"."deal_products" to "authenticated";

grant select on table "public"."deal_products" to "authenticated";

grant trigger on table "public"."deal_products" to "authenticated";

grant truncate on table "public"."deal_products" to "authenticated";

grant update on table "public"."deal_products" to "authenticated";

grant delete on table "public"."deal_products" to "service_role";

grant insert on table "public"."deal_products" to "service_role";

grant references on table "public"."deal_products" to "service_role";

grant select on table "public"."deal_products" to "service_role";

grant trigger on table "public"."deal_products" to "service_role";

grant truncate on table "public"."deal_products" to "service_role";

grant update on table "public"."deal_products" to "service_role";

grant delete on table "public"."deal_services" to "anon";

grant insert on table "public"."deal_services" to "anon";

grant references on table "public"."deal_services" to "anon";

grant select on table "public"."deal_services" to "anon";

grant trigger on table "public"."deal_services" to "anon";

grant truncate on table "public"."deal_services" to "anon";

grant update on table "public"."deal_services" to "anon";

grant delete on table "public"."deal_services" to "authenticated";

grant insert on table "public"."deal_services" to "authenticated";

grant references on table "public"."deal_services" to "authenticated";

grant select on table "public"."deal_services" to "authenticated";

grant trigger on table "public"."deal_services" to "authenticated";

grant truncate on table "public"."deal_services" to "authenticated";

grant update on table "public"."deal_services" to "authenticated";

grant delete on table "public"."deal_services" to "service_role";

grant insert on table "public"."deal_services" to "service_role";

grant references on table "public"."deal_services" to "service_role";

grant select on table "public"."deal_services" to "service_role";

grant trigger on table "public"."deal_services" to "service_role";

grant truncate on table "public"."deal_services" to "service_role";

grant update on table "public"."deal_services" to "service_role";

grant delete on table "public"."maintenance_contracts" to "anon";

grant insert on table "public"."maintenance_contracts" to "anon";

grant references on table "public"."maintenance_contracts" to "anon";

grant select on table "public"."maintenance_contracts" to "anon";

grant trigger on table "public"."maintenance_contracts" to "anon";

grant truncate on table "public"."maintenance_contracts" to "anon";

grant update on table "public"."maintenance_contracts" to "anon";

grant delete on table "public"."maintenance_contracts" to "authenticated";

grant insert on table "public"."maintenance_contracts" to "authenticated";

grant references on table "public"."maintenance_contracts" to "authenticated";

grant select on table "public"."maintenance_contracts" to "authenticated";

grant trigger on table "public"."maintenance_contracts" to "authenticated";

grant truncate on table "public"."maintenance_contracts" to "authenticated";

grant update on table "public"."maintenance_contracts" to "authenticated";

grant delete on table "public"."maintenance_contracts" to "service_role";

grant insert on table "public"."maintenance_contracts" to "service_role";

grant references on table "public"."maintenance_contracts" to "service_role";

grant select on table "public"."maintenance_contracts" to "service_role";

grant trigger on table "public"."maintenance_contracts" to "service_role";

grant truncate on table "public"."maintenance_contracts" to "service_role";

grant update on table "public"."maintenance_contracts" to "service_role";

grant delete on table "public"."products" to "anon";

grant insert on table "public"."products" to "anon";

grant references on table "public"."products" to "anon";

grant select on table "public"."products" to "anon";

grant trigger on table "public"."products" to "anon";

grant truncate on table "public"."products" to "anon";

grant update on table "public"."products" to "anon";

grant delete on table "public"."products" to "authenticated";

grant insert on table "public"."products" to "authenticated";

grant references on table "public"."products" to "authenticated";

grant select on table "public"."products" to "authenticated";

grant trigger on table "public"."products" to "authenticated";

grant truncate on table "public"."products" to "authenticated";

grant update on table "public"."products" to "authenticated";

grant delete on table "public"."products" to "service_role";

grant insert on table "public"."products" to "service_role";

grant references on table "public"."products" to "service_role";

grant select on table "public"."products" to "service_role";

grant trigger on table "public"."products" to "service_role";

grant truncate on table "public"."products" to "service_role";

grant update on table "public"."products" to "service_role";

grant delete on table "public"."services" to "anon";

grant insert on table "public"."services" to "anon";

grant references on table "public"."services" to "anon";

grant select on table "public"."services" to "anon";

grant trigger on table "public"."services" to "anon";

grant truncate on table "public"."services" to "anon";

grant update on table "public"."services" to "anon";

grant delete on table "public"."services" to "authenticated";

grant insert on table "public"."services" to "authenticated";

grant references on table "public"."services" to "authenticated";

grant select on table "public"."services" to "authenticated";

grant trigger on table "public"."services" to "authenticated";

grant truncate on table "public"."services" to "authenticated";

grant update on table "public"."services" to "authenticated";

grant delete on table "public"."services" to "service_role";

grant insert on table "public"."services" to "service_role";

grant references on table "public"."services" to "service_role";

grant select on table "public"."services" to "service_role";

grant trigger on table "public"."services" to "service_role";

grant truncate on table "public"."services" to "service_role";

grant update on table "public"."services" to "service_role";


  create policy "Deal Products Delete Policy"
  on "public"."deal_products"
  as permissive
  for delete
  to authenticated
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."deal_products"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for authenticated users"
  on "public"."deal_products"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable update for authenticated users only"
  on "public"."deal_products"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "Deal Services Delete Policy"
  on "public"."deal_services"
  as permissive
  for delete
  to authenticated
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."deal_services"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for authenticated users"
  on "public"."deal_services"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable update for authenticated users only"
  on "public"."deal_services"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "Enable insert for authenticated users only"
  on "public"."maintenance_contracts"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for authenticated users"
  on "public"."maintenance_contracts"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable update for authenticated users only"
  on "public"."maintenance_contracts"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "Maintenance Contracts Delete Policy"
  on "public"."maintenance_contracts"
  as permissive
  for delete
  to authenticated
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."products"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for authenticated users"
  on "public"."products"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable update for authenticated users only"
  on "public"."products"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "Products Delete Policy"
  on "public"."products"
  as permissive
  for delete
  to authenticated
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."services"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for authenticated users"
  on "public"."services"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable update for authenticated users only"
  on "public"."services"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "Services Delete Policy"
  on "public"."services"
  as permissive
  for delete
  to authenticated
using (true);


CREATE TRIGGER on_deal_won_create_maintenance_contracts AFTER UPDATE ON public.deals FOR EACH ROW EXECUTE FUNCTION public.create_maintenance_contracts_on_win();


